<?php

use Illuminate\Database\Seeder;

class MedicosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        DB::table('medicos')->insert(array (
            0 =>
            array (
                'crm' => '73413',
                'nome' => 'Luiz Marcelo Aiello Viarengo',
                'email' => 'drluizmarcel@gmail.com',
                'password' => NULL,
                'telefone' => '1145864444',
                'cep' => '13208056',
                'endereco' => 'Av Nove de Julho',
                'numero' => '1717',
                'complemento' => 'Conj 42 Ed Saint Georges',
                'bairro' => 'Vila Boaventura',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            1 =>
            array (
                'crm' => '26195',
                'nome' => 'Marco Antonio Herculano',
                'email' => 'drmarcoantonio@gmail.com',
                'password' => NULL,
                'telefone' => '1145834776',
                'cep' => '13209000',
                'endereco' => 'Rua do Retiro',
                'numero' => '424',
                'complemento' => NULL,
                'bairro' => 'Vila Virginia',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            2 =>
            array (
                'crm' => '96233',
                'nome' => 'Fábio Luis Fujita',
                'email' => 'drfabioluis@gmail.com',
                'password' => NULL,
                'telefone' => '1144970651',
                'cep' => '13201843',
                'endereco' => 'Av Antonio Segre',
                'numero' => '333',
                'complemento' => NULL,
                'bairro' => 'Jardim Brasil',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            3 =>
            array (
                'crm' => '83762',
                'nome' => 'Elizeu de Sousa Santos',
                'email' => 'drelizeu@gmail.com',
                'password' => NULL,
                'telefone' => '1198367886',
                'cep' => '13208761',
                'endereco' => 'Rua Barão de Teffé',
                'numero' => '1000',
                'complemento' => '2 andar, sala 21',
                'bairro' => 'Jardim Ana Maria',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            4 =>
            array (
                'crm' => '88579',
                'nome' => 'João Carlos Gonzalez Gonzalez',
                'email' => 'drjoao@gmail.com',
                'password' => NULL,
                'telefone' => '1145869288',
                'cep' => '13207130',
                'endereco' => 'Rua Atilio Vianelo',
                'numero' => '310',
                'complemento' => NULL,
                'bairro' => 'Vianelo',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            5 =>
            array (
                'crm' => '63151',
                'nome' => 'João Augusto Fernandes Gonçalves',
                'email' => 'drjoaoaugusto@gmail.com',
                'password' => NULL,
                'telefone' => '1145227237',
                'cep' => '13208140',
                'endereco' => 'Rua Abilio Figueiredo',
                'numero' => '92',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            6 =>
            array (
                'crm' => '113297',
                'nome' => 'Pedro Guilherme Meinberg',
                'email' => 'drpedro@gmail.com',
                'password' => NULL,
                'telefone' => '1145213155',
                'cep' => '13209000',
                'endereco' => 'Rua do Retiro',
                'numero' => '432',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            7 =>
            array (
                'crm' => '67787',
                'nome' => 'Wilson Scappini Junior',
                'email' => 'drwilson@gmail.com',
                'password' => NULL,
                'telefone' => '1145230595',
                'cep' => '13201098',
                'endereco' => 'Rua Vasco da Gama',
                'numero' => '23',
                'complemento' => NULL,
                'bairro' => 'Vila Municipal',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            8 =>
            array (
                'crm' => '137141',
                'nome' => 'Eder Deivis Fistarol',
                'email' => 'dreder@gmail.com',
                'password' => NULL,
                'telefone' => '1148071024',
                'cep' => '13201838',
                'endereco' => 'Rua Sócrates Fernandes de Oliveira',
                'numero' => '45',
                'complemento' => NULL,
                'bairro' => 'Chacara Urbana',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            9 =>
            array (
                'crm' => '115386',
                'nome' => 'Luciano Takenori Nishimaru',
                'email' => 'drluciano@gmail.com',
                'password' => NULL,
                'telefone' => '1145213155',
                'cep' => '13208761',
                'endereco' => 'Rua Barão de Teffé',
                'numero' => '1000',
                'complemento' => 'sala 52',
                'bairro' => 'Jardim Ana Maria',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            10 =>
            array (
                'crm' => '98709',
                'nome' => 'José Antônio Ustra Zaquia Alam',
                'email' => 'drjose@gmail.com',
                'password' => NULL,
                'telefone' => '1145834776',
                'cep' => '13209000',
                'endereco' => 'Rua do Retiro',
                'numero' => '424',
                'complemento' => NULL,
                'bairro' => 'Vila Virginia',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            11 =>
            array (
                'crm' => '102002',
                'nome' => 'Alessandro Nakanishi Bastos',
                'email' => 'dralessandro@gmail.com',
                'password' => NULL,
                'telefone' => '1148071024',
                'cep' => '13200000',
                'endereco' => 'Rua Socrates Fernandes de Oliveira',
                'numero' => '45',
                'complemento' => NULL,
                'bairro' => 'Chacara Urbana',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            12 =>
            array (
                'crm' => '66463',
                'nome' => 'Maurício Baldissin',
                'email' => 'drmauricio@gmail.com',
                'password' => NULL,
                'telefone' => '1145217121',
                'cep' => '13208760',
                'endereco' => 'Rua Barão de Teffe',
                'numero' => '160',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            13 =>
            array (
                'crm' => '104139',
                'nome' => 'Patricia Ferreira de Carvalho',
                'email' => 'drapatricia@gmail.com',
                'password' => NULL,
                'telefone' => '1148072240',
                'cep' => '13208060',
                'endereco' => 'Av Amadeu Ribeiro',
                'numero' => '265',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            14 =>
            array (
                'crm' => '124262',
                'nome' => 'Erika Vick Fernandes Gomes',
                'email' => 'draerika@gmail.com',
                'password' => NULL,
                'telefone' => '11984974855',
                'cep' => '13201796',
                'endereco' => 'Rua Ademar Pereira de Barros',
                'numero' => '21',
                'complemento' => NULL,
                'bairro' => 'Centro',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            15 =>
            array (
                'crm' => '129483',
                'nome' => 'Camila de Melo Campos',
                'email' => 'dracamila@gmail.com',
                'password' => NULL,
                'telefone' => '1148072240',
                'cep' => '13208060',
                'endereco' => 'Av Amadeu Ribeiro',
                'numero' => '265',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            16 =>
            array (
                'crm' => '79998',
                'nome' => 'Marcelo Brancalhao Tojar',
                'email' => 'drmarcelo@gmail.com',
                'password' => NULL,
                'telefone' => '1148052700',
                'cep' => '13201043',
                'endereco' => 'Rua Conrado Augusto Offa',
                'numero' => '80',
                'complemento' => NULL,
                'bairro' => 'Chacara Urbana',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            17 =>
            array (
                'crm' => '108576',
                'nome' => 'Lauro Schledorn de Camargo',
                'email' => 'drlauro@gmail.com',
                'password' => NULL,
                'telefone' => '11944450022',
                'cep' => '13208056',
                'endereco' => 'Av 9 de julho',
                'numero' => '2575',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            18 =>
            array (
                'crm' => '26252',
                'nome' => 'Edmir Américo Lourenço',
                'email' => 'dredmir@gmail.com',
                'password' => NULL,
                'telefone' => '1145211697',
                'cep' => '13209000',
                'endereco' => 'Rua do Retiro',
                'numero' => '424',
                'complemento' => NULL,
                'bairro' => 'Vilia VIirginia',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            19 =>
            array (
                'crm' => '114657',
                'nome' => 'Alexandre Cabral Zilli',
                'email' => 'dralexandre@gmail.com',
                'password' => NULL,
                'telefone' => '1145261837',
                'cep' => '13206810',
                'endereco' => 'Rua Portugal',
                'numero' => '295',
                'complemento' => NULL,
                'bairro' => 'Jardim Cica',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            20 =>
            array (
                'crm' => '108742',
                'nome' => 'Maurilio Jorge Cruz Junior',
                'email' => 'drmaurilio@gmail.com',
                'password' => NULL,
                'telefone' => '1128162705',
                'cep' => '13207270',
                'endereco' => 'Rua Bom Jesus de Pirapora',
                'numero' => '315',
                'complemento' => NULL,
                'bairro' => 'Vianelo',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            21 =>
            array (
                'crm' => '139810',
                'nome' => 'Roberto Giordano',
                'email' => 'drroberto@gmail.com',
                'password' => NULL,
                'telefone' => '1148072240',
                'cep' => '13208060',
                'endereco' => 'Rua Amadeu Ribeiro',
                'numero' => '265',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            22 =>
            array (
                'crm' => '147503',
                'nome' => 'Marcella Ledo Martins Costa',
                'email' => 'dramarcela@gmail.com',
                'password' => NULL,
                'telefone' => '1144970033',
                'cep' => '13201796',
                'endereco' => 'Av 9 de julho',
                'numero' => '32',
                'complemento' => NULL,
                'bairro' => 'Anhangabau',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            23 =>
            array (
                'crm' => '116494',
                'nome' => 'Bianca Zanchetta Buani Miguel',
                'email' => 'drabianca@gmail.com',
                'password' => NULL,
                'telefone' => '1145214798',
                'cep' => '13209090',
                'endereco' => 'Rua Eduardo Tomanik',
                'numero' => '900',
                'complemento' => NULL,
                'bairro' => 'Chacara Urbana',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
            24 =>
            array (
                'crm' => '140984',
                'nome' => 'Elias Flato',
                'email' => 'drelias@gmail.com',
                'password' => NULL,
                'telefone' => '11940130333',
                'cep' => '13207060',
                'endereco' => 'Rua Conde de Monsanto',
                'numero' => '483',
                'complemento' => NULL,
                'bairro' => 'Vianelo',
                'cidade' => 'Jundiai',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			25 =>
            array (
                'crm' => '23679',
                'nome' => 'Dr. Francisco Antonio Monteiro Fazano',
                'email' => 'Francisco@gmail.com',
                'password' => 123456,
                'telefone' => '1532320479 ',
                'cep' => '18035257',
                'endereco' => 'Rua Dr. Nogueira Martins',
                'numero' => '230',
                'complemento' => NULL,
                'bairro' => 'Centro',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			26 =>
            array (
                'crm' => '21533',
                'nome' => 'Dra. Paula Maria Preto Mimura',
                'email' => 'Paula@gmail.com',
                'password' => 123456,
                'telefone' => '1532116296',
                'cep' => '18090010',
                'endereco' => 'Dr Braulio Guedes da Silva',
                'numero' => '86',
                'complemento' => NULL,
                'bairro' => 'Santa Rosalia',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			27 =>
            array (
                'crm' => '51629',
                'nome' => 'Dr. Luiz Tarciso da Gama',
                'email' => 'Luiz@gmail.com',
                'password' => 123456,
                'telefone' => '1532027524',
                'cep' => '18046790',
                'endereco' => 'Rua La Plata',
                'numero' => '21',
                'complemento' => NULL,
                'bairro' => 'Jardim America',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			28 =>
            array (
                'crm' => '79434',
                'nome' => 'Dr. Newton José Borba Canicoba',
                'email' => 'Newton@gmail.com',
                'password' => 123456,
                'telefone' => '1532333477',
                'cep' => '18090000',
                'endereco' => 'Av. Roberto Simonsen',
                'numero' => '445',
                'complemento' => NULL,
                'bairro' => 'Santa Rosalia',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			29 =>
            array (
                'crm' => '130374',
                'nome' => 'Dr. Lineu Amaro Rodrigues Junior',
                'email' => 'Lineu@gmail.com',
                'password' => 123456,
                'telefone' => '1532335743',
                'cep' => '18030205',
                'endereco' => 'Rua Antônio Cândido Pereira',
                'numero' => '21',
                'complemento' => NULL,
                'bairro' => 'Jd. Faculdade',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			30 =>
            array (
                'crm' => '0070428',
                'nome' => 'Dra. Valdiza de Moura Casagrande',
                'email' => 'Valdiza@gmail.com',
                'password' => 123456,
                'telefone' => '1532113793',
                'cep' => '18030130',
                'endereco' => 'Salvador Correia',
                'numero' => '658',
                'complemento' => NULL,
                'bairro' => 'Jd. Vergueiro',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			31 =>
            array (
                'crm' => '132554',
                'nome' => 'Dr. Brunno Cezar Framil Sanches',
                'email' => 'Brunno@gmail.com',
                'password' => 123456,
                'telefone' => '1532335743',
                'cep' => '18030205',
                'endereco' => 'Rua Antônio Cândido Pereira',
                'numero' => '21',
                'complemento' => NULL,
                'bairro' => 'Jd. Faculdade',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			32 =>
            array (
                'crm' => '128574',
                'nome' => 'Dr. Ana Cláudia Ghiraldi Alves',
                'email' => 'Ana@gmail.com',
                'password' => 123456,
                'telefone' => '1533318282',
                'cep' => '18040560',
                'endereco' => 'Capitão Grandino',
                'numero' => '269',
                'complemento' => NULL,
                'bairro' => 'Oeste',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
			33 =>
            array (
                'crm' => '125596',
                'nome' => 'Dra. Larissa Teles Sanches',
                'email' => 'Larissa@gmail.com',
                'password' => 123456,
                'telefone' => '1533318282',
                'cep' => '18047-380',
                'endereco' => 'José Maria Barbosa',
                'numero' => '31',
                'complemento' => NULL,
                'bairro' => 'Campolim',
                'cidade' => 'Sorocaba',
                'estado' => 'SP',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'foto' => NULL,
            ),
        ));
    }
}
